#!/bin/sh
#AccuWeather (r) RSS weather tool for conky
#
#USAGE: weather.sh UKXX0062
#
#(c) Michael Seiler 2007
 
METRIC=1 #Should be 0 or 1; 0 for F, 1 for C
 
if [ -z $1 ]; then
echo
echo "USAGE: weather <locationcode>"
echo
exit 0;
fi
out=$(curl -s http://rss.accuweather.com/rss/liveweather_rss.asp\?metric\=${METRIC}\&locCode\=$1 |  perl -ne 'if (/Currently/) {chomp;/\<title\>Currently: (.*)?\<\/title\>/; print "$1"; }')
first=$(echo $out | perl -ne '/(.*): /; print "$1"')
temp=$(echo $out | perl -ne '/: (\d*)C/; print "$1"')
echo "$out"
echo

color=$(sh ~/.i3/color_chart $temp)
echo "#$color"
