(function(){function D(e){var u=!1,f=4,k,B,I,y,v,D=function(){u=!0;I=[0,1,2,4,8,16,32,64,128,27,54];for(var b=Array(256),d=0;128>d;++d)b[d]=d<<1,b[d+128]=d+128<<1^283;k=Array(256);B=Array(256);y=Array(4);v=Array(4);for(d=0;4>d;++d)y[d]=Array(256),v[d]=Array(256);for(var m=0,c=0,f,l,e,g,s,d=0;256>d;++d){g=c^c<<1^c<<2^c<<3^c<<4;g=g>>8^g&255^99;k[m]=g;B[g]=m;s=b[g];f=b[m];l=b[f];e=b[l];s^=s<<24^g<<16^g<<8^g;l=(f^l^e)<<24^(m^e)<<16^(m^l^e)<<8^m^f^e;for(var h=0;4>h;++h)y[h][m]=s,v[h][g]=l,s=s<<24|s>>>
8,l=l<<24|l>>>8;0===m?m=c=1:(m=f^b[b[b[f^e]]],c^=b[b[c]])}},G=function(b,d){for(var m=b.slice(0),c,e=1,l=m.length,x=f*(l+6+1),g=l;g<x;++g)c=m[g-1],0===g%l?(c=k[c>>>16&255]<<24^k[c>>>8&255]<<16^k[c&255]<<8^k[c>>>24]^I[e]<<24,e++):6<l&&4===g%l&&(c=k[c>>>24]<<24^k[c>>>16&255]<<16^k[c>>>8&255]<<8^k[c&255]),m[g]=m[g-l]^c;if(d){for(var e=v[0],l=v[1],s=v[2],h=v[3],n=m.slice(0),x=m.length,g=0,p=x-f;g<x;g+=f,p-=f)if(0===g||g===x-f)n[g]=m[p],n[g+1]=m[p+3],n[g+2]=m[p+2],n[g+3]=m[p+1];else for(var r=0;r<f;++r)c=
m[p+r],n[g+(3&-r)]=e[k[c>>>24]]^l[k[c>>>16&255]]^s[k[c>>>8&255]]^h[k[c&255]];m=n}return m},E=function(b,d,f,c){var e=b.length/4-1,l,x,g,s,h;c?(l=v[0],x=v[1],g=v[2],s=v[3],h=B):(l=y[0],x=y[1],g=y[2],s=y[3],h=k);var n,p,r,u,J,A;n=d[0]^b[0];p=d[c?3:1]^b[1];r=d[2]^b[2];d=d[c?1:3]^b[3];for(var q=3,w=1;w<e;++w)u=l[n>>>24]^x[p>>>16&255]^g[r>>>8&255]^s[d&255]^b[++q],J=l[p>>>24]^x[r>>>16&255]^g[d>>>8&255]^s[n&255]^b[++q],A=l[r>>>24]^x[d>>>16&255]^g[n>>>8&255]^s[p&255]^b[++q],d=l[d>>>24]^x[n>>>16&255]^g[p>>>
8&255]^s[r&255]^b[++q],n=u,p=J,r=A;f[0]=h[n>>>24]<<24^h[p>>>16&255]<<16^h[r>>>8&255]<<8^h[d&255]^b[++q];f[c?3:1]=h[p>>>24]<<24^h[r>>>16&255]<<16^h[d>>>8&255]<<8^h[n&255]^b[++q];f[2]=h[r>>>24]<<24^h[d>>>16&255]<<16^h[n>>>8&255]<<8^h[p&255]^b[++q];f[c?1:3]=h[d>>>24]<<24^h[n>>>16&255]<<16^h[p>>>8&255]<<8^h[r&255]^b[++q]},H=function(b,d,m,c,k){function l(){if(c)for(var a=0;a<f;++a)t[a]=q.getInt32();else for(a=0;a<f;++a)t[a]=C[a]^q.getInt32();E(B,t,z,c);if(c){for(a=0;a<f;++a)w.putInt32(C[a]^z[a]);C=t.slice(0)}else{for(a=
0;a<f;++a)w.putInt32(z[a]);C=z}}function x(){E(B,t,z,!1);for(var a=0;a<f;++a)t[a]=q.getInt32();for(a=0;a<f;++a){var b=t[a]^z[a];c||(t[a]=b);w.putInt32(b)}}function g(){E(B,t,z,!1);for(var a=0;a<f;++a)t[a]=q.getInt32();for(a=0;a<f;++a)w.putInt32(t[a]^z[a]),t[a]=z[a]}function s(){E(B,t,z,!1);for(var a=f-1;0<=a;--a)if(4294967295===t[a])t[a]=0;else{++t[a];break}for(a=0;a<f;++a)w.putInt32(q.getInt32()^z[a])}var h=null;u||D();k=(k||"CBC").toUpperCase();if("string"===typeof b&&(16===b.length||24===b.length||
32===b.length))b=e.util.createBuffer(b);else if(e.util.isArray(b)&&(16===b.length||24===b.length||32===b.length)){var n=b;b=e.util.createBuffer();for(var p=0;p<n.length;++p)b.putByte(n[p])}if(!e.util.isArray(b)){n=b;b=[];var r=n.length();if(16===r||24===r||32===r)for(r>>>=2,p=0;p<r;++p)b.push(n.getInt32())}if(!e.util.isArray(b)||4!==b.length&&6!==b.length&&8!==b.length)return h;var n=-1!==["CFB","OFB","CTR"].indexOf(k),v="CBC"===k,B=G(b,c&&!n),A=f<<2,q,w,t,z,C,y,F,h={output:null};if("CBC"===k)F=l;
else if("CFB"===k)F=x;else if("OFB"===k)F=g;else if("CTR"===k)F=s;else throw{message:'Unsupported block cipher mode of operation: "'+k+'"'};h.update=function(a){for(y||q.putBuffer(a);q.length()>=A||0<q.length()&&y;)F()};h.finish=function(a){var b=!0,d=q.length()%A;if(!c)if(a)b=a(A,q,c);else if(v){var e=q.length()===A?A:A-q.length();q.fillWithByte(e,e)}b&&(y=!0,h.update());c&&(v&&(b=0===d),b&&(a?b=a(A,w,c):v&&(e=w.length(),e=w.at(e-1),e>f<<2?b=!1:w.truncate(e))));!v&&!a&&0<d&&w.truncate(A-d);return b};
h.start=function(a,b){null===a&&(a=C.slice(0));if("string"===typeof a&&16===a.length)a=e.util.createBuffer(a);else if(e.util.isArray(a)&&16===a.length){var d=a;a=e.util.createBuffer();for(var c=0;16>c;++c)a.putByte(d[c])}e.util.isArray(a)||(d=a,a=Array(4),a[0]=d.getInt32(),a[1]=d.getInt32(),a[2]=d.getInt32(),a[3]=d.getInt32());q=e.util.createBuffer();w=b||e.util.createBuffer();C=a.slice(0);t=Array(f);z=Array(f);y=!1;h.output=w;if(-1!==["CFB","OFB","CTR"].indexOf(k)){for(c=0;c<f;++c)t[c]=C[c];C=null}};
null!==d&&h.start(d,m);return h};e.aes=e.aes||{};e.aes.startEncrypting=function(b,d,e,c){return H(b,d,e,!1,c)};e.aes.createEncryptionCipher=function(b,d){return H(b,null,null,!1,d)};e.aes.startDecrypting=function(b,d,e,c){return H(b,d,e,!0,c)};e.aes.createDecryptionCipher=function(b,d){return H(b,null,null,!0,d)};e.aes._expandKey=function(b,d){u||D();return G(b,d)};e.aes._updateBlock=E}if("function"!==typeof define)if("object"===typeof module&&module.exports){var L=!0;define=function(e,u){u(require,
module)}}else return"undefined"===typeof forge&&(forge={}),D(forge);var G,M=function(e,u){u.exports=function(f){var k=G.map(function(f){return e(f)}).concat(D);f=f||{};f.defined=f.defined||{};if(f.defined.aes)return f.aes;f.defined.aes=!0;for(var u=0;u<k.length;++u)k[u](f);return f.aes}},K=define;define=function(e,u){G="string"===typeof e?u.slice(2):e.slice(2);if(L)return delete define,K.apply(null,Array.prototype.slice.call(arguments,0));define=K;return define.apply(null,Array.prototype.slice.call(arguments,
0))};define(["require","module","./util"],function(){M.apply(null,Array.prototype.slice.call(arguments,0))})})();
