window.requestFileSystem||(window.requestFileSystem=window.webkitRequestFileSystem);window.BlobBuilder||(window.BlobBuilder=window.WebKitBlobBuilder);
Registry.require("promise layout xmlhttprequest convert crcrc curtain layout/default/tabview layout/default/htmlutil helper i18n parser statistics layout/default/layout_helper".split(" "),function(){var H=rea.FEATURES,I=Registry.get("promise"),m=Registry.get("crcrc").cr,d=Registry.get("crcrc").crc,k=Registry.get("i18n"),u=Registry.get("curtain"),q=Registry.get("helper"),J=Registry.get("layout/default/tabview"),t=Registry.get("layout/default/htmlutil"),K=Registry.get("statistics"),y=Registry.get("layout"),
z=Registry.get("layout/default/layout_helper"),B=z.images;y.render(function(){z.addStyle();z.addFont();var h=null,C="???",v=null,D="0.0.0",w=function(){var a=document.getElementById("ask"),c=d("div","main_container p100100","ask","main");if(a){var b=a.parentNode;b.removeChild(a);b.appendChild(c);document.body.setAttribute("class","main")}var a=d("div","head_container","ask","head_container"),b=d("div","tv_container","ask","tv_container"),g=m("a","head_link","ask","head_link");g.href="http://tampermonkey.net";
g.target="_blank";var e=d("div","float margin4","ask","head1"),f=d("img","banner","ask");f.src=rea.extension.getURL("images/icon128.png");var n=d("div","float head margin4","ask","head2"),k=m("div","heading"),h=d("div","version","version","version");h.textContent=" by Jan Biniok";var s=m("div","search","box","");k.textContent="Tampermonkey";e.appendChild(f);n.appendChild(k);n.appendChild(h);g.appendChild(e);g.appendChild(n);a.appendChild(g);a.appendChild(s);c.appendChild(a);c.appendChild(b);c=J.create("_main",
b);a=m("div","main","main","tab_content_h");a.textContent=C;b=m("div","main","main","tab_content");c.appendTab(q.createUniqueId("main","main"),a,b).select();u.hide();return b},y=function(a){var c=a.script,b=d("div","viewer_bottom","bottom","");a=d("div","editor_400p_outer","editor",c.name);var g=d("div","editor_400p editor_border","editor",c.name);b.appendChild(a);a.appendChild(g);h.nocm?(a=d("textarea","editorta","editor",c.name),a.setAttribute("wrap","off"),g.appendChild(a),a.value=c.textContent):
window.setTimeout(function(){b.editor=new MirrorFrame(g,{value:c.textContent,noButtons:!0,matchBrackets:!0})},1);return b},L=function(){var a={};window.addEventListener("keydown",function(c){var b=!1;if("keydown"==c.type&&(a[c.keyCode]&&(b=a[c.keyCode](c)),b))return c.stopPropagation(),c.preventDefault(),!1},!0);return{registerListener:function(c,b){a[c]=b}}}(),x=function(a,c,b){q.select(b,function(a){return a.label}).forEach(function(b){var e=d("input",c,"tm",b.label);e.type="button";e.value=b.label;
e.addEventListener("click",b.fn);a.appendChild(e);b.focus&&window.setTimeout(function(){$(e).focus()},300);b.keyDown&&L.registerListener(b.keyDown.keyCode?b.keyDown.keyCode:b.keyDown,b.keyDown.cb?b.keyDown.cb:b.fn)})},O=function(a){var c=a.script,b=d("div","viewer_last","install"),g=d("div","viewer_content","install_content"),e=d("div","ask_action_buttons","install_buttons"),f=[];f.push({label:a.messages.action,fn:M,focus:!0});H.RUNTIME.CHROME&&f.push({label:a.messages.flags.install?k.getMessage("Process_with_Chrome"):
null,fn:function(){N(c.fileURL);$(b).hide()}});f.push({label:k.getMessage("Cancel"),fn:r,keyDown:27});x(e,"install",f);g.appendChild(e);b.appendChild(g);return b},P=function(a){var c=d("div","viewer_last","import"),b=d("div","viewer_content","import_content"),g=d("div","ask_action_buttons","import_buttons");x(g,"import",[{label:k.getMessage("Import"),fn:function(){var b=Object.keys(a);p(h.aid,"import",{data:{import_ids:b}})},focus:!0},{label:k.getMessage("Cancel"),fn:r,keyDown:27}]);b.appendChild(g);
c.appendChild(b);return c},Q=function(a){a=d("div","viewer_last","ok");var c=d("div","viewer_content","ok_content"),b=d("div","ask_action_buttons","ok_buttons");x(b,"import",[{label:k.getMessage("Ok"),fn:r,focus:!0}]);c.appendChild(b);a.appendChild(c);return a},R=function(a,c){var b=d("div","viewer_last","ok"),g=d("div","viewer_content","ok_content"),e=d("div","ask_action_buttons","ok_buttons");x(e,"permission",[{label:k.getMessage("Ok"),fn:function(){rea.permissions.request({permissions:[c.permission]},
function(a){rea.runtime.lastError&&console.warn("notify: error on getting permission",c.permission+"!","reason:",rea.runtime.lastError.message);p(h.aid,"permission",{data:{granted:a,permission:c.permission}})})},focus:!0},{label:k.getMessage("Cancel"),fn:r,keyDown:27}]);g.appendChild(e);b.appendChild(g);var g=d("div","viewer_upper","permission"),e=d("div","viewer_info","general","permission"),f=d("div","viewer_content","general_content","permission"),n=m("h3","install","heading","permission"),E=d("span",
"message","heading","permission");n.textContent=c.title;E.textContent=c.message;f.appendChild(E);e.appendChild(n);e.appendChild(f);g.appendChild(e);a.appendChild(g);a.appendChild(b)},A=function(a,c){var b=a.preparat,g=a.content,e=b.script||{},f=e.uuid||e.id||e.name;b.short_info||(b.short_info=[]);var n=d("div","viewer_upper",f),h=d("div","viewer_info","general",f),p=d("div","viewer_content","general_content",f),s=m("h3","install","heading",f);if(e.icon||e.icon64){var l=m("img","version","heading",
f);l.src=e.icon||e.icon64;s.appendChild(l)}l=m("span","name","heading",f);l.textContent=b.heading||e.name||"";s.appendChild(l);e.version&&(l=d("span","view_version","heading",f),l.textContent="v"==e.version[0]?"":"v",l.textContent+=e.version,s.appendChild(l));h.appendChild(s);c&&b.short_info.unshift({prop:"heading",value:b.messages.heading,label:k.getMessage("Action")});var r=d("table","script_desc",f);b.short_info.forEach(function(a){var b=e[a.prop]||a.value;if(b||!c){var g=d("tr","script_desc",
a.prop,f),n=d("td","script_desc",a.prop,f+"dt"),h=d("td","script_desc",a.prop,f+"dd");n.textContent=a.label?a.label:"";h.textContent=b||k.getMessage("_not_set_");g.appendChild(n);g.appendChild(h);r.appendChild(g)}});p.appendChild(r);var s=d("div","viewer_info","info",f),q;c?q=p:(q=d("div","viewer_content","info_content",f),l=m("h4","action","heading",f),l.textContent=b.messages.heading,q.appendChild(l));["errors","warnings","info"].forEach(function(a){var c=m("table",a,f);(b.messages[a]||[]).forEach(function(b){var d=
m("tr",a,f),e=m("td",a,f+"dt"),g=m("td",a,f+"dd");"info"==a?(e.textContent=b.label,g.textContent=b.value):"warnings"==a?(e.innerHTML='<img src="'+B.get("critical")+'"></img>&nbsp;',g.innerHTML=t.safeTagsReplace(b).replace(/\n/,"<br />")):"errors"==a&&(e.innerHTML='<img src="'+B.get("error")+'"></img>&nbsp;',g.innerHTML=t.safeTagsReplace(b).replace(/\n/,"<br />"));d.appendChild(e);d.appendChild(g);c.appendChild(d)});q.appendChild(c)});l=function(a,b,c,g){var n=m("table",a,f),h=0,l={};b.forEach(function(b){if(!(h>
g||l[b])){l[b]=!0;var e=d("tr",a+"desc",b,f+h),k=d("td",a+"desc",b,f+h+"dt"),m=d("td",a+"desc",b,f+h+"dd");k.innerHTML=0==h?t.safeTagsReplace(c.label):"&nbsp;";m.innerHTML=h==g?'<span title="'+t.safeTagsReplace(c.warning)+'">...!</span>':t.safeTagsReplace(b);e.appendChild(k);e.appendChild(m);n.appendChild(e);h++}});if(e.options&&(b=e.options.override&&e.options.override["use_"+a])&&b.length){b=d("tr",a+"desc","ovverride",f+h);var p=d("td",a+"desc","ovverride",f+h+"dt"),r=d("td",a+"desc","ovverride",
f+h+"dd");p.innerHTML=0==h?t.safeTagsReplace(c.label):"&nbsp;";r.innerHTML=t.safeTagsReplace(" ("+k.getMessage("overwritten_by_user")+")");b.appendChild(p);b.appendChild(r);n.appendChild(b)}q.appendChild(n)};l("includes",(e.includes||[]).concat(e.matches||[]),{label:k.getMessage("Include_s__"),warning:k.getMessage("Attention_Can_not_display_all_includes_")},5);l("excludes",e.excludes||[],{label:k.getMessage("Exclude_s__"),warning:k.getMessage("Attention_Can_not_display_all_excludes_")},3);h.appendChild(p);
s.appendChild(q);n.appendChild(h);n.appendChild(s);g.appendChild(n);a.install&&g.appendChild(a.install(b));a.editor&&g.appendChild(a.editor(b))},N=function(a){p(h.aid,"abort");window.setTimeout(function(){window.location=a+"#bypass=true"},10)},r=function(a,c){p(h.aid,"abort");window.setTimeout(function(){window.close()},100)},F=function(a,c){p(h.aid,"unload");v&&(window.clearInterval(v),v=null);window.removeEventListener("unload",F)};window.addEventListener("unload",F);var G=function(){window.location.search||
window.location.hash?(h=q.getUrlArgs(),h.aid?(p(h.aid,"preparat").done(function(a){a.ext&&a.ext.version&&(D=a.ext.version);a.i18n&&k.setLocale(a.i18n);a.options&&a.options.statistics_enabled&&K.init("ask",D);C=k.getMessage("Install");var c=null;a.preparat&&("install"==a.type?c=function(){A({content:w(),preparat:a.preparat,install:O,editor:y})}:"install_error"==a.type?c=function(){A({content:w(),preparat:a.preparat,install:Q},!0)}:"import"==a.type?c=function(){var b=w(),c=a.preparat;b.appendChild(P(c));
for(var e in c){var f=c[e],h=d("div","viewer_upper",e);A({content:h,preparat:f},!0);b.appendChild(h)}}:"permission"==a.type&&(c=function(){R(w(),a.preparat)}),v=window.setInterval(S,6E4),c&&window.setTimeout(c,1))}).fail(function(){r()}),u.wait(k.getMessage("Please_wait___"))):r()):window.onhashchange=function(){G()}},S=function(){return p(h.aid,"ping",{bg:!0})},M=function(){return p(h.aid,"install")},p=function(a,c,b){b=b||{};var d=I();try{var e={aid:a,method:c};b.data&&q.each(b.data,function(a,
c){e[c]=b.data[c]});sendMessage({method:"askCom",data:e},function(a){b.bg||u.hide();a.error?("close"==a.action&&r(),d.reject(a)):d.resolve(a)});b.bg||u.wait(k.getMessage("Please_wait___"))}catch(f){console.warn("sS: "+f.message),d.reject()}return d.promise()};rea.extension.onMessage.addListener(function(a,c,b){if("confirm"==a.method)q.confirm(a.msg,function(a){b({confirm:a})});else if("showMsg"==a.method)q.alert(a.msg),b({});else return!1;return!0});G()})});
