#!/bin/sh
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi


# Use bash_aliases
if [ -f ~/.bash_aliases ]; then
		. ~/.bash_aliases
fi

setxkbmap dk
exec i3
xrdb -merge ~/.Xresources
