# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
setopt appendhistory nomatch
unsetopt beep
bindkey -v
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/home/elmegaard/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall

# Zsh to use the same colors as ls
zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}

alias ls='ls --color=auto'
alias tma='tmux attach-session -t'
alias tmux='tmux -2'

case $TERM in
    xterm*)
        precmd () {print -Pn "\e]0;$PWD\a"}
        ;;
esac


#PATH
export PATH="$PATH:/usr/local/texlive/2014/bin/x86_64-linux"
export GOPATH=$HOME/go
export PATH="$PATH:$GOPATH/bin"
export DOTSCRIPTS="$HOME/git/LinuxConfig/laptop/scripts"

# thefuck
eval "$(thefuck --alias fuck)"

# python env
venv() {
    local activate=~/.python/$1/bin/activate
    if [ -e "$activate" ] ; then
        source "$activate"
    else
        echo "Error: Not found: $activate"
    fi
}
venv27() { venv 27 ; }

source "$DOTSCRIPTS/zsh-git-prompt/zshrc.sh"
PROMPT='%B%m%~%b$(git_super_status) %# '
