Registry.registerRaw("environment.js","3",function(){Context.domContentLoaded=!1;Context.loadHappened=!1;Context.domNodeInserted=!1;Context.props={};Context.adjustLogLevel=function(a){void 0!==a&&(logLevel=a);D|=60<=logLevel};var q=function(){var a={objs:{},push:function(b,c){0!==c&&1!==c&&(c=0);var d=Math.floor(19831206*Math.random()+1);a.objs[d]={fn:b,prio:c};return d},remove:function(b){delete a.objs[b]},get:function(b){for(var c=[],d=0;1>=d;d++)for(var h in a.objs)a.objs.hasOwnProperty(h)&&
(a.objs[h].prio!==d||void 0!==b&&h!=b||c.push(a.objs[h].fn));return void 0===b?c:c[0]},finalize:function(b){if(void 0===b){b=a.get();for(var c=0;c<b.length;c++)b[c]()}else return a.objs[b]&&(c=a.objs[b].fn(),delete a.objs[b]),c}};return a}();Context.adjustLogLevel();var K=function(a){return{}.toString.apply(a).match(/\s([a-z|A-Z]+)/)[1]},A=function(a,b){void 0==b&&(b=100);return b&&a&&(a==document||A(a.parentNode,b-1))},O=function(){var a=function(){};a.prototype={};return new a},Y=function(){var a=
O(),b=function(a,c,d,b,e,k){var f=d[b];d[b]=k&&"string"===typeof f?new Function(f):function(){return f.apply(e,arguments)};return c.apply(a,d)},c={setTimeout:{enhance:function(){return b(window,safeWindow.setTimeout,arguments,0,a,!0)}},setInterval:{enhance:function(){return b(window,safeWindow.setInterval,arguments,0,a,!0)}},close:{get:function(){return window.self==window.top?function(a){return X(a)}:window.close}},location:{get:!0,set:function(a){window.location.href=a}},clearInterval:{get:function(){return safeWindow.clearInterval}},
clearTimeout:{get:function(){return safeWindow.clearTimeout}},addEventListener:{enhance:function(){return b(window,safeWindow.addEventListener,arguments,1,a,!0)}},removeEventListener:{enhance:function(){return b(window,safeWindow.removeEventListener,arguments,1,a,!0)}}},d=function(c){return c==window?a:c},h=function(a,c,d,b){d||(d=a);var e=function(){var e=a[c].apply(d,arguments);b&&(e=b(e));return e};e.__proto__=a[c];e.prototype=a[c].prototype;return e},f=function(c){var d,e,b=null,b=function(b){d=
b;e=function(){return b.apply(a,arguments)};window[c]=e};a.__defineGetter__(c,function(){return void 0===d||e!==window[c]?window[c]:d});a.__defineSetter__(c,b)},g=function(c,b,e){var f,k=null,h=null,k="function"===typeof b.get?b.get:function(){e&&e.get_cb&&e.get_cb.apply(this,arguments);return void 0===f?d(window[c]):f};"function"===typeof b.set?h=b.set:b.get||(h=function(a){e&&e.set_cb&&e.set_cb.apply(this,arguments);f=a});k&&a.__defineGetter__(c,k);h&&a.__defineSetter__(c,h)};(function(){var a=
0,c=function(c){for(var b=a;b<c;b++)g(String(b),{get:!0});a=Math.max(c,a)};g("length",{},{get_cb:function(){c(window.frames.length)}});c(Math.max(window.frames.length,7))})();for(var e in c)c.hasOwnProperty(e)&&(Context.windowProps[e]=Context.windowProps[e]||!1!==c[e]);var k;for(e in Context.windowProps)if(Context.windowProps.hasOwnProperty(e)&&!1!==c[e]){k={};try{try{c[e]?c[e].wrap?(k.wrap=!0,k.that=c[e].that):c[e].direct?k.direct=!0:c[e].enhance?k.enhance=c[e].enhance:c[e].get&&(k.get=c[e].get,
k.set=c[e].set):"function"===typeof window[e]?Context.windowProps[e].proto?k.wrap=!0:k.direct=!0:"number"===typeof window[e]||"string"===typeof window[e]?k.get=!0:Context.windowProps[e].event&&Context.windowProps[e].proto?k.event=!0:k.direct=!0}catch(u){k.get=!0}k.direct?a[e]=d(window[e]):k.enhance?a[e]=k.enhance:k.event?f(e):k.get||k.set?g(e,k):k.wrap&&function(){var c=e;a[c]=h(window,c,k.that,d)}()}catch(p){console.warn("env: error while creating a new sandbox: "+p.message)}}B(a,1);return a},Z=
function(a,b,c,d,h){var f=null;try{var g=d.sandboxes[a.uuid];g.__TMbackref||(g.__TMbackref={});var e='arguments.callee.__tmid = { uuid: "'+a.uuid+'", run_at: "'+a.options.run_at+'" };\n',k=["context"],u=[void 0],p;for(p in d.elements[a.uuid])if(d.elements[a.uuid].hasOwnProperty(p)){var n=d.elements[a.uuid][p];n.name?n.overwrite?(k.push(n.name),u.push(n.value)):n.scriptid?(g.__TMbackref[n.name+"_"+n.scriptid]=n.value,k.push(n.name),u.push('context.__TMbackref["'+n.name+"_"+n.scriptid+'"]')):(g[n.name]=
n.value,k.push(n.name),u.push("context."+n.name)):D&&console.warn("env: WARN: unexpected item in props elem: "+JSON.stringify(n))}f=[e,"with (context) {\n(function(",k.join(","),") {try {\n",c,b,"\n} catch (e) {if (e.message && e.stack) {console.error(\"ERROR: Execution of script '",a.name.replace(/(['"])/g,"\\$1"),'\' failed! " + e.message);console.log(e.stack.replace(/(\\\\(eval at )?<anonymous>[: ]?)|([\\s.]*at TM_mEval[\\s\\S.]*)/g, ""));} else {console.error(e);}};\n}).apply(context, [',u.join(","),
"]);}\n"].join("");d=function(a,c){(new Function("context",f)).apply(c,[c])};h?h(d,[f,g]):d(f,g)}catch(l){chromeEmu.extension.sendMessage({method:"syntaxCheck",code:[c,b].join("")},function(e){var d="";if(e.errors){var d=c.split("\n").length-1,f="",k;for(k in e.errors){var h=e.errors[k];if(h&&0<=h.line&&h.reason)var g=h.line,f=f+[g>d?"script:":"require:"," (",h.code,") ",h.reason.replace(/.$/,"")," on line: ",g>d?g-d:g," at character: ",h.character,"\n"].join("")}d="JSHINT output:\n"+f}else d=b;k=
l.stack?l.stack.replace(/(\\(eval at )?<anonymous>[: ]?)|([\s.]*at TM_mEval[\s\S.]*)/g,""):"";D||e.errors?console.error("Syntax error @ '"+a.name+"'!\n##########################\n"+d+"##########################\n\n"+k):console.error("Syntax error @ '"+a.name+"'!\n\n",k);safeWindow.setTimeout(function(){D&&chromeEmu.extension.sendMessage({method:"copyToClipboard",data:{content:b,type:"test"},id:"42"},function(){});throw l;},1)})}},v=[],l={events:[],done:{},running:null},w=function(a,b,c,d){var h={attrChange:0,
attrName:null,bubbles:!0,cancelBubble:!1,cancelable:!1,clipboardData:void 0,currentTarget:null,defaultPrevented:!1,eventPhase:0,newValue:null,prevValue:null,relatedNode:null,returnValue:!0,srcElement:null,target:null,timeStamp:(new Date).getTime()};c="string"===typeof c?new Function(c):c;var f=new Event,g;for(g in h)f[g]=h[g];for(g in b)f[g]=b[g];f.type=a;c.apply(d,[f])},C=function(){Context.loadHappened=!0;Context.domContentLoaded=!0;D&&console.log("env: DOMContentLoaded Event!");y()},E=function(a){Context.domNodeInserted||
!D||console.log("env: first DOMNodeInserted Event!");Context.loadHappened=!0;Context.domNodeInserted=!0;l&&l.events.push({event:a,domContentLoaded:Context.domContentLoaded})},F=function(a){Context.loadHappened=!0;D&&console.log("env: load Event!")},G=function(){safeDocument.removeEventListener("DOMNodeInserted",E,!1);safeDocument.removeEventListener("DOMContentLoaded",C,!1);safeDocument.removeEventListener("load",F,!1);safeWindow.removeEventListener("unload",G,!1);if(null!=q){for(var a=q.get(),b=
0;b<a.length;b++)a[b]();q=null}chromeEmu.clean&&chromeEmu.clean()},y=function(){for(var a=v.length;0<v.length;){var b=v.shift();try{safeWindow.setTimeout(b.fn,1)}catch(c){console.log("ERROR: Execution (loadListener) of script env "+b.name+" failed!"+c.message)}}return a},H=function(a,b){if(document.body)safeWindow.setTimeout(function(){a()},1);else{var c=function(){safeDocument.removeEventListener("load",c,!1);safeDocument.removeEventListener("DOMNodeInserted",c,!1);safeDocument.removeEventListener("DOMContentLoaded",
c,!1);H(a,b)};safeDocument.addEventListener("load",c,!1);safeDocument.addEventListener("DOMNodeInserted",c,!1);safeDocument.addEventListener("DOMContentLoaded",c,!1)}},$=function(a,b,c){v.push({fn:function(){a()},name:c});Context.domContentLoaded?y():D&&console.log("env: schedule for later events!")},s=[],B=function(a,b){if(!a.__addEventListener){a.__addEventListener=a.addEventListener;a.__removeEventListener=a.removeEventListener;a.removeEventListener=function(a,c,b){"DOMNodeInserted"==a&&l&&l.running==
c&&(l.running=null);this.__removeEventListener(a,c,b)};var c=function(a,c,b,g){if(c){var e=s.length;c=parseInt(["DOMContentLoaded"==b?1:2,g?1:2,g?c:3-c,(new Date).getTime()].join("0"));for(b=0;b<s.length;b++)if(g=s[b],!g||!g.prio||g.prio>c){e=b;break}s.splice(e,0,{prio:c,fn:a})}else s.push({fn:a})};a.addEventListener=function(a,h,f){var g=!0;if("load"==a||"DOMContentLoaded"==a||"DOMNodeInserted"==a){var e=null,k=this;try{e=I(arguments.callee)}catch(u){D&&console.error("env: Error: event "+a,u)}if(e){var p=
null;"load"==a?Context.loadHappened&&(p=function(){w("load",{attrName:"null",newValue:"null",prevValue:"null",eventPhase:Event.AT_TARGET,attrChange:MutationEvent.ADDITION,target:document,relatedNode:document,srcElement:document},h,k)},g=!1,c(p,b,a,f)):"DOMContentLoaded"==a?Context.domContentLoaded&&(p=function(){w("DOMContentLoaded",{attrName:"null",newValue:"null",prevValue:"null",eventPhase:Event.AT_TARGET,attrChange:MutationEvent.ADDITION,target:document,relatedNode:document,srcElement:document},
h,k)},g=!1,c(p,b,a,f)):"DOMNodeInserted"==a&&l&&!l.done[e.uuid]&&(l.done[e.uuid]=!0,p=function(){var c="document-start"!=e.run_at&&"document-body"!=e.run_at;l.running=h;if(l.running){a:if(l)for(var b=l.events.length,g=0;g<b;g++)if(c&&!l.events[g].domContentLoaded||w("DOMNodeInserted",{attrName:"",newValue:"",prevValue:"",eventPhase:Event.AT_TARGET,target:l.events[g].event.target,relatedNode:l.events[g].event.relatedNode,srcElement:l.events[g].event.srcElement},h,k),!l.running)break a;k.__addEventListener(a,
h,f)}l.running=null},c(p));p&&(safeWindow.setTimeout(function(){if(s.length){var a=s.shift();a&&a.fn&&a.fn()}},1),g=!1)}}g&&this.__addEventListener(a,h,f)};q.push(function(){a.removeEventListener=a.__removeEventListener;a.addEventListener=a.__addEventListener})}Context.windowProps.__addEventListener={proto:!0};Context.windowProps.__removeEventListener={proto:!0}},I=function(a,b){void 0===b&&(b=20);return 0==b?null:!a.__tmid&&a.caller?I(a.caller,b-1):a.__tmid},P=function(a){q.finalize(a)},M=function(a,
b,c){var d=TM_context_id+"#"+a,h=null,h=q.push(function(){chromeEmu.extension.sendMessage({method:"unRegisterMenuCmd",name:a,id:d},function(a){})},1);chromeEmu.extension.sendMessage({method:"registerMenuCmd",name:a,id:TM_context_id,menuId:d,accessKey:c},function(d){d.run&&null!==h&&void 0!==q.get(h)?(safeWindow.setTimeout(function(){b()},1),M(a,b,c)):null!==h&&(q.remove(h),h=null)});return h},Q=function(a,b){var c=!1,d=null,h=chromeEmu.extension.connect("openInTab_"+TM_context_id);a&&0==a.search(/^\/\//)&&
(a=window.location.protocol+a);h.onMessage.addListener(function(a){a.tabId?c&&f():a.close&&(c=!0,d&&(d(),d=void 0))});h.onDisconnect.addListener(function(){h=null});h.postMessage({method:"openInTab",details:{url:a,id:TM_context_id,options:b},id:TM_context_id});var f=function(){h&&h.postMessage({method:"closeTab",id:TM_context_id})},g={close:function(){c?D&&console.debug("env: attempt to close already closed tab!"):(c=!0,f())}};g.__defineGetter__("closed",function(){return c});g.__defineGetter__("onclose",
function(){return d});g.__defineSetter__("onclose",function(a){d=a});return g},R=function(a,b){var c=!1,d="Object"===K(a)?a:{url:a,name:b};d.url&&"/"===d.url[0]&&(d.url=window.location.origin+d.url);var h=d.context;delete d.context;var f=chromeEmu.extension.connect("download_"+TM_context_id);f.postMessage({method:"download",details:d,id:TM_context_id});var g=function(a,b){b=b||{};a&&!c&&safeWindow.setTimeout(function(){a.apply(b,[b])},1)};f.onMessage.addListener(function(a){try{a.data&&h&&(a.data.context=
h),a.success?d.onload&&(a.data.responseXML&&(a.data.responseXML=safeWindow.unescape(a.data.responseXML)),g(d.onload,a.data)):a.progress?d.onprogress&&g(d.onprogress,a.data):a.timeout?d.ontimeout&&g(d.ontimeout,a.data):d.onerror&&g(d.onerror,a.data)}catch(c){console.log("env: Error: TM_download - ",c,d)}});return{abort:function(){c=!0}}},S=function(a){var b=!1;a.url&&"/"===a.url[0]&&(a.url=window.location.origin+a.url);var c=a.context;delete a.context;var d=function(){var a={};Object.getOwnPropertyNames(XMLHttpRequest.__proto__).forEach(function(c){a[c]=
!0});var c=function(){};Object.getOwnPropertyNames(XMLHttpRequest).forEach(function(b){a[b]||(c[b]=XMLHttpRequest[b])});return c}(),h=function(a,c){c=c||{};a&&!b&&safeWindow.setTimeout(function(){c.__proto__=d;a.apply(c,[c])},1)};if("FormData"!==K(a.data)){var f=chromeEmu.extension.connect("xhr_"+TM_context_id),g=[];f.postMessage({method:"xhr",details:a,id:TM_context_id});f.onMessage.addListener(function(b){try{if(b.data&&c&&(b.data.context=c),b.success){if(a.onload){g.length&&(b.data.response_data=
g.join(""),g=null);if(b.data.response_data){var d=b.data.response_data,e=b.data.response_types;["response_data","response_types"].forEach(function(a){delete b.data[a]});if(e){var f={response:function(b){var c=a.responseType?a.responseType.toLowerCase():"",d=function(a){for(var c=new Uint8Array(a.length),d=0;d<a.length;d++)c[d]=b.charCodeAt(d);return c.buffer};return"arraybuffer"==c?d(b):"blob"==c?new Blob([d(b)]):"json"==c?JSON.parse(b):b},responseText:function(a){return a},responseXML:function(a){return(new DOMParser).parseFromString(a,
"text/xml")}},l;for(l in f)if(f.hasOwnProperty(l))if(e[l])try{b.data[l]=f[l](d)}catch(q){console.warn("GM_xmlhttpRequest: ",q)}else b.data[l]=null}else console.warn("GM_xmlhttpRequest: got unusual response!"),b.data.responseText=d}a.onreadystatechange&&h(a.onreadystatechange,b.data);h(a.onload,b.data)}}else b.change?a.onreadystatechange&&4!=b.data.readyState&&h(a.onreadystatechange,b.data):b.progress?a.onprogress&&h(a.onprogress,b.data):b.partial?g.push(b.data.partial):b.timeout?a.ontimeout&&h(a.ontimeout,
b.data):a.onerror&&h(a.onerror,b.data)}catch(s){console.log("env: Error: TM_xmlhttpRequest",s,a)}})}else{var e=new XMLHttpRequest;void 0===a.async&&(a.async=!0);e.open(a.method,a.url,a.async,a.user,a.password);if(a.headers)for(f in a.headers)e.setRequestHeader(f,a.headers[f]);a.overrideMimeType&&e.overrideMimeType(a.overrideMimeType);a.responseType&&(e.responseType=a.responseType);"abort error load progress readystatechange timeout".split(" ").forEach(function(b){e["on"+b]=function(){var d="",f=a.url;
if(2<e.readyState&&(d=e.getAllResponseHeaders(),4==e.readyState)){d&&(d=d.replace(/TM-finalURL\: .*[\r\n]{1,2}/,""));var g=e.getResponseHeader("TM-finalURL");g&&(f=g)}d={readyState:e.readyState,status:"",statusText:"",responseHeaders:d,finalUrl:f,context:c};4==e.readyState&&(e.responseType&&""!=e.responseType?d.response=e.response:(d.responseText=e.responseText,d.responseXML=e.responseXML),d.status=e.status,d.statusText=e.statusText);h(a["on"+b],d)}});e.send(a.data)}return{abort:function(){b=!0}}},
T=function(a,b){chromeEmu.extension.sendMessage({method:"installScript",url:a,id:TM_context_id},function(a){b&&b(a)})},X=function(a){chromeEmu.extension.sendMessage({method:"closeTab",id:TM_context_id},function(b){b.error&&console.warn(b.error);a&&a()})},aa=function(a,b){var c=[],d=a.storage,h=a.script.uuid,f=a.script,g=null;(function(){g=chromeEmu.extension.connect("storageListener_"+TM_context_id);g.onMessage.addListener(function(a){if(a.storage)for(var c in a.storage.data)if(a.storage.data.hasOwnProperty(c)){var e=
d.data[c];d.data[c]=a.storage.data[c];l(c,e,d.data[c],!0)}a.removed&&(d[a.removed]=b);a.error&&console.log("env: Error: storage listener... :(")});g.postMessage({method:"addStorageListener",uuid:h,id:TM_context_id})})();var e=function(a){g.postMessage({method:"saveStorageKey",uuid:h,key:a,value:d.data[a],id:TM_context_id,ts:d.ts})},k=function(a,c,d){d===b&&(d=function(a){return a});var e=[],f=null;if(a&&a.length){var f={GM_info:!0},g;for(g in a)if(a.hasOwnProperty(g)){var h=a[g];f[h]=!0}}for(g in c)c.hasOwnProperty(g)&&
(h=c[g],f&&!f[d(h.name)]||e.push(h));return e},l=function(a,b,d,e){if(b!=d)for(var f in c)if(c.hasOwnProperty(f)){var g=c[f];if(g&&g.key==a&&g.cb)try{g.cb(a,w(b),w(d),e)}catch(h){D&&console.warn("env: value change listener of '"+a+"' failed with: "+h.message)}}},p=function(a,b){var d=0,e;for(e in c)c.hasOwnProperty(e)&&c[e].id>d&&(d=e.id);d++;c.push({id:d,key:a,cb:b});return d},n=function(a){for(var b in c)if(c.hasOwnProperty(b)&&c[b].id==a)return delete c[b],!0},s=function(a){var b=d.data[a];d.ts=
(new Date).getTime();delete d.data[a];e(a);l(a,b,d.data[a],!1)},v=function(){var a=[],b;for(b in d.data)d.data.hasOwnProperty(b)&&a.push(b);return a},w=function(a,b){if("string"===typeof a){var c=a[0];a=a.substring(1);switch(c){case "b":return"true"===a;case "n":return Number(a);case "o":try{return JSON.parse(a)}catch(d){console.log("env: parseValueFromStorage: "+d)}return b;default:return a}}else return b},y=function(a,b){return w(d.data[a],b)},A=function(a,b){var c=d.data[a],f=(typeof b)[0];switch(f){case "o":try{b=
f+JSON.stringify(b)}catch(g){console.log(g);return}break;default:b=f+b}d.ts=(new Date).getTime();d.data[a]=b;e(a);l(a,c,d.data[a],!1)},B=function(a){for(var b in f.resources){var c=f.resources[b];if(c.name==a)return c.resText}return null},C=function(a){for(var b in f.resources){var c=f.resources[b];if(c.name==a)return c.resURL}return null},E=function(a){console.log(a)},F=function(a){try{var b=safeDocument.createElement("style");b.textContent=a;(document.head||document.body||document.documentElement||
document).appendChild(b);return b}catch(c){console.log("Error: env: adding style "+c)}},G=function(b,c,d,e,f){var g=null,h={method:"notification",id:TM_context_id},k=["timeout","text","image","title","highlight"],l=null;"object"===typeof b?l=b:"object"===typeof f&&(l=f);l?(k.forEach(function(a){h[a]=l[a]}),g=l.ondone,e=l.onclick,"function"===typeof c&&(g=c)):("number"===typeof f&&(h.timeout=f),h.image=d,h.title=c,h.text=b);h.text&&(h.image=h.image||a.script.icon64||a.script.icon,h.title=h.title||
a.script.name);h.text||h.highlight?chromeEmu.extension.sendMessage(h,function(a){e&&a.clicked&&e();g&&g(!0===a.clicked)}):console.warn("TM_notification: neither a message text nor the hightlight options was given!")},H=function(a,b,c){var d=typeof b,e="text",f="text/plain";"object"===d?(b.type&&(e=b.type),b.mimetype&&(f=b.mimetype)):"string"===d&&(e=b);chromeEmu.extension.sendMessage({method:"copyToClipboard",data:{content:a,type:e,mimetype:f},id:TM_context_id},function(a){c&&c()})},I=function(a){chromeEmu.extension.sendMessage({method:"getTab",
id:TM_context_id,uid:f.uuid},function(b){a&&a(b.data)})},L=function(a,b){chromeEmu.extension.sendMessage({method:"setTab",id:TM_context_id,tab:a,uid:f.uuid},function(a){b&&b()})},U=function(a){chromeEmu.extension.sendMessage({method:"getTabs",id:TM_context_id,uid:f.uuid},function(b){a&&a(b.data)})},m=function(a,b){var c=window,d="__u__"+Math.floor(19831206*Math.random()+1),e=d+"_";c[d]=a;c[e]=b;var f=Context.eval.call(window,'window["'+d+'"].apply(this, window["'+e+'"])');delete c[d];delete c[e];
return f},r=[],x=null,t;for(t in f.grant)if(f.grant.hasOwnProperty(t)&&"none"===f.grant[t]){x=m;break}var z=f.namespace+"_"+!!x;Context.props[z]===b&&(Context.props[z]={sandboxes:{},elements:{}},q.push(function(){Context.props[z]=null}));if(!x){r.push({name:"window",value:"context",overwrite:!0});var N={window:window};for(t in N)N.hasOwnProperty(t)&&function(){var a=t.replace(/^(.)/g,function(a){return a.toUpperCase()});r.push({name:"unsafe"+a,value:N[t]})}()}r.push({name:"CDATA",value:function(a){this.src=
a;this.toXMLString=this.toString=function(){return this.src}}});r.push({name:"uneval",value:function(a){try{return"\\$1 = "+JSON.stringify(a)+";"}catch(b){console.log(b)}}});r.push({name:"undefined",value:b});r.push({name:"define",value:b});r.push({name:"module",value:b});r.push({name:"console",value:console});x||(r.push({name:"cloneInto",value:function(a,b,c){return a}}),r.push({name:"exportFunction",value:function(a,c,d){d&&d.defineAs!==b&&(c[d.defineAs]=a);return a}}),r.push({name:"createObjectIn",
value:function(a,c){var d={};c&&c.defineAs!==b&&(a[c.defineAs]=d);return d}}));m=[];m.push({name:"TM_addStyle",value:F});m.push({name:"TM_deleteValue",value:s});m.push({name:"TM_listValues",value:v});m.push({name:"TM_getValue",value:y});m.push({name:"TM_log",value:E});m.push({name:"TM_registerMenuCommand",value:M});m.push({name:"TM_unregisterMenuCommand",value:P});m.push({name:"TM_openInTab",value:Q});m.push({name:"TM_setValue",value:A});m.push({name:"TM_addValueChangeListener",value:p});m.push({name:"TM_removeValueChangeListener",
value:n});m.push({name:"TM_xmlhttpRequest",value:S});m.push({name:"TM_download",value:R});m.push({name:"TM_setClipboard",value:H});m.push({name:"TM_getTab",value:I});m.push({name:"TM_setTab",value:L});m.push({name:"TM_saveTab",value:L});m.push({name:"TM_getTabs",value:U});m.push({name:"TM_installScript",value:T});m.push({name:"TM_notification",value:G});m.push({name:"TM_getResourceText",value:B,scriptid:f.uuid});m.push({name:"TM_getResourceURL",value:C,scriptid:f.uuid});var J=[],V=new function(){this.GM_addStyle=
function(a){return F(a)};this.GM_deleteValue=function(a){return s(a)};this.GM_listValues=function(){return v()};this.GM_getValue=function(a,b){return y(a,b)};this.GM_addValueChangeListener=function(a,b){return p(a,b)};this.GM_removeValueChangeListener=function(a){return n(a)};this.GM_log=function(a){return E(a)};this.GM_registerMenuCommand=function(a,b,c){return M(a,b,c)};this.GM_unregisterMenuCommand=function(a){return P(a)};this.GM_openInTab=function(a,b){return Q(a,b)};this.GM_setValue=function(a,
b){return A(a,b)};this.GM_xmlhttpRequest=function(a){return S(a)};this.GM_download=function(){return R.apply(this,arguments)};this.GM_getResourceText=function(a){return B(a)};this.GM_getResourceURL=function(a){return C(a)};this.GM_notification=function(a,b,c,d,e){return G(a,b,c,d,e)};this.GM_installScript=function(a,b){return T(a,b)};this.GM_getTab=function(a){return I(a)};this.GM_setTab=function(a,b){return L(a,b)};this.GM_saveTab=function(a){return L(a)};this.GM_getTabs=function(a){return U(a)};
this.GM_setClipboard=function(a,b,c){return H(a,b,c)};Object.defineProperties(this,{GM_info:{get:function(){var b={observers:1,id:1,enabled:1,hash:1,fileURL:1},c={script:{}},d;for(d in f)f.hasOwnProperty(d)&&!b[d]&&(c.script[d]=f[d]);b=f.options.updateURL||f.options.fileURL;c.script["run-at"]=f.options.override.run_at||f.options.run_at;c.script.excludes=f.options.override.orig_excludes;c.script.includes=f.options.override.orig_includes;c.script.matches=f.options.override.orig_includes;c.script.grant=
f.grant;c.script.unwrap=!1;c.scriptMetaStr=a.header;c.scriptSource=a.code;c.scriptWillUpdate=!!b;c.scriptUpdateURL=b;c.version=a.version;c.scriptHandler="Tampermonkey";c.isIncognito=Context.isIncognito;return c},enumerable:!0,configurable:!0}})},W=[];for(t in V)W.push({name:t,value:V[t]});J=J.concat(k(f.grant,m,function(a){return a.replace(/^TM_/,"GM_")}));J=J.concat(k(f.grant,W));r=r.concat(J);f.options.compat_prototypes&&(D&&console.log("env: option: add toSource"),Object.prototype.toSource||Object.defineProperties(Object.prototype,
{toSource:{value:function(){var a=K(this);if("String"===a)return"(String('"+this.replace(/\'/g,"\\'")+"'))";if("Number"===a)return"(Number('"+Number(this)+"'))";if("Array"===a){for(var b="(new Array(",c=0;c<this.length;c++)a=K(this[c]),b="Null"===a?b+"null":"Undefined"===a?b+"undefined":b+this[c].toSource(),c+1<this.length&&(b+=",");return b+"))"}return"JSON.parse(unescape('"+safeWindow.escape(JSON.stringify(this))+"'))"},enumerable:!1,writable:!0,configurable:!0}}),D&&console.log("env: option: add some array generics"),
"indexOf lastIndexOf filter forEach every map some slice".split(" ").forEach(function(a){if("function"!==typeof Array[a]){var b={};b[a]={value:function(b){return Array.prototype[a].apply(b,Array.prototype.slice.call(arguments,1))},enumerable:!1,writable:!0,configurable:!0};Object.defineProperties(Array,b)}}));Context.props[z].sandboxes[a.script.uuid]=x?O():Y();Context.props[z].elements[a.script.uuid]=r;D&&console.debug("env: execute script "+f.name+" @ the "+(x?"un":"")+"safe context now!");Z(f,a.code,
a.requires,Context.props[z],x);q.push(function(){g.postMessage({method:"removeStorageListener",uuid:h,storage:d,id:TM_context_id});try{g.disconnect(),g=null}catch(b){}a=c=null})};chromeEmu.extension.onMessage.addListener(function(a,b,c){if(a.id&&a.id!=TM_context_id)console.warn("env: Not for me! "+TM_context_id+"!="+a.id);else if(b=window.self==window.top,"executeScript"==a.method)b=function(){aa(a);c({})},"document-start"==a.script.options.run_at?(D&&console.debug("env: run '"+a.script.name+"' ASAP -> document-start"),
b()):"document-body"==a.script.options.run_at?(D&&console.debug("env: schedule '"+a.script.name+"' for document-body"),H(b,a.script.uuid)):(D&&console.debug("env: schedule '"+a.script.name+"' for document-end"),$(b,a.script.uuid,a.script.name));else if("onLoad"==a.method){Context.domContentLoaded=!0;y();c({});var d=null,h=function(){l=d=null};q.push(function(){d&&safeWindow.clearTimeout(d);h()});d=safeWindow.setTimeout(h,2E3)}else b&&("loadUrl"==a.method?(window.location=a.url,c({})):"reload"==a.method?
(window.location.reload(),c({})):"confirm"==a.method?safeWindow.setTimeout(function(){var b=safeWindow.confirm(a.msg);c({confirm:b})},100):"showMsg"==a.method?safeWindow.setTimeout(function(){safeWindow.setTimeout(function(){safeWindow.alert(a.msg)},1);c({})},100):console.log("env: unknown method "+a.method))});(function(a){a.__evaluate||(a.__evaluate=a.evaluate,a.evaluate=function(a,c,d,h,f){c||(c=this);var g;if("undefined"!=typeof XPathResult){var e=null;try{g=this.__evaluate(a,c,d,h,f)}catch(k){e=
k}var l=!1;try{l|=!!g.snapshotLength}catch(p){}try{l|=!!g.singleNodeValue}catch(n){}if(!l&&"."!=a.charAt(0)&&!A(c)){a=("/"==a.charAt(0)?".":"./")+a;try{g=this.__evaluate(a,c,d,h,f)}catch(q){}}if(!l&&e)throw e;}else g=c.selectNodes(a);return g},q.push(function(){a.evaluate=a.__evaluate}))})(window.HTMLDocument.prototype);B(window.HTMLDocument.prototype,2);safeDocument.addEventListener("DOMContentLoaded",C,!1);safeDocument.addEventListener("load",F,!1);safeDocument.addEventListener("DOMNodeInserted",
E,!1);safeWindow.addEventListener("unload",G,!1);D&&console.debug("env: initialized (content, id:"+TM_context_id+", "+window.location.origin+window.location.pathname+") ")});
